name: AI News Bot Daily Run

on:
  schedule:
    # Runs every 6 hours (00:00, 06:00, 12:00, 18:00 UTC)
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # IMPORTANT: Point this to your HEAVY requirements file
          pip install -r requirements_github.txt

      - name: Create Google Credentials File
        run: echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" > credentials.json

      - name: Run AI Crew
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
        run: python main.py
